{% set name = "flasgger" %}
{% set version = "0.9.7.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: ca098e10bfbb12f047acc6299cc70a33851943a746e550d86e65e60d4df245fb

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python 2.7|>=3.6
    - pip
    - setuptools
  run:
    - flask >=0.10
    - jsonschema >=3.0.1
    - mistune
    - python 2.7|>=3.6
    - pyyaml >=3.0
    - six >=1.10.0


test:
  imports:
    - flasgger

about:
  home: https://github.com/rochacbruno/flasgger
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Easy Swagger UI for your Flask API

extra:
  recipe-maintainers:
    - lvoliveira
    - nicoddemus
    - igortg
